/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerInfo {
  'name' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface LineItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'lineItems' : Array<LineItem>,
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : bigint,
  'customer' : CustomerInfo,
  'createdAt' : Time,
  'createdBy' : Principal,
  'subtotal' : bigint,
  'transactionId' : [] | [string],
}
export type OrderId = bigint;
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'paymentVerified' : null };
export type PaymentMethod = { 'cashOnDelivery' : null } |
  { 'easyPaisa' : null } |
  { 'jazzCash' : null };
export interface Product {
  'id' : ProductId,
  'active' : boolean,
  'name' : string,
  'description' : string,
  'price' : bigint,
  'images' : Array<string>,
}
export type ProductId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[OrderId], undefined>,
  'confirmOrder' : ActorMethod<[OrderId], undefined>,
  'createOrder' : ActorMethod<
    [
      CustomerInfo,
      Array<LineItem>,
      bigint,
      bigint,
      PaymentMethod,
      [] | [string],
    ],
    Order
  >,
  'createProduct' : ActorMethod<
    [string, string, bigint, Array<string>],
    Product
  >,
  'deactivateProduct' : ActorMethod<[ProductId], undefined>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOrderDelivered' : ActorMethod<[OrderId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, bigint, Array<string>, boolean],
    Product
  >,
  'uploadProductImage' : ActorMethod<
    [ExternalBlob, ProductId, string],
    ExternalBlob
  >,
  'verifyPayment' : ActorMethod<[OrderId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];